#ifndef INCLUDE_MSPIO_UARTIO_MSG_H
#define INCLUDE_MSPIO_UARTIO_MSG_H

#define UARTIO_MSG_TYPE_PRINTF_STR 0x0
#define UARTIO_MSG_TYPE_BYTES 0x1
#define UARTIO_MSG_TYPE_MAT 0x2

#define UARTIO_BUFFER_SIZE 100
#define UARTIO_16BIT_BUFFER_SIZE UARTIO_BUFFER_SIZE / 2

#endif /* INCLUDE_MSPIO_UARTIO_MSG_H */